const SET_INGREDIENTS = 'SET_INGREDIENTS';
const SET_ALLINGREDIENTS = 'SET_ALLINGREDIENTS';
const SET_ORDERDATA = 'SET_ORDERDATA';
const SET_CURRENT = 'SET_CURRENT';
const REMOVE_CURRENT = 'SET_CURRENT';

const UPDATE_COUNTER = 'UPDATE_COUNTER';
const INCREASE_DROPPEDELEMENT = 'INCREASE_DROPPEDELEMENT';
const CHANGE_POSITION='CHANGE_POSITION';

const SET_IFMOBILE = 'SET_IFMOBILE';

const DELETE_ITEM = 'DELETE_ITEM';
const SET_DROPDIRECTION= 'SET_DROPDIRECTION';

const SET_DRAGGEDCONSTRUCTOR= 'SET_DRAGGEDCONSTRUCTOR';

const SET_TOTALSUM = 'SET_TOTALSUM';

const REPLACE_BUN = 'REPLACE_BUN';

export {
  SET_INGREDIENTS,
  SET_ALLINGREDIENTS,
  SET_ORDERDATA,
  SET_CURRENT,
  REMOVE_CURRENT,
  SET_IFMOBILE,
  UPDATE_COUNTER,
  INCREASE_DROPPEDELEMENT,
  CHANGE_POSITION,
  DELETE_ITEM,
  SET_DROPDIRECTION,
  SET_DRAGGEDCONSTRUCTOR,
  SET_TOTALSUM,
REPLACE_BUN

};
