const SET_INGREDIENTS = 'SET_INGREDIENTS';
const SET_ALLINGREDIENTS = 'SET_ALLINGREDIENTS';
const SET_ORDERDATA = 'SET_ORDERDATA';
const SET_CURRENT = 'SET_CURRENT';
const REMOVE_CURRENT = 'SET_CURRENT';

const UPDATE_COUNTER = 'UPDATE_COUNTER';
const INCREASE_DROPPEDELEMENT = 'INCREASE_DROPPEDELEMENT';

const SET_IFMOBILE = 'SET_IFMOBILE';

export {
  SET_INGREDIENTS,
  SET_ALLINGREDIENTS,
  SET_ORDERDATA,
  SET_CURRENT,
  REMOVE_CURRENT,
  SET_IFMOBILE,
  UPDATE_COUNTER,
  INCREASE_DROPPEDELEMENT,
};
