const SET_INGREDIENTSBYCAT = 'SET_INGREDIENTSBYCAT';

const SET_ORDERDATA = 'SET_ORDERDATA';
const SET_CURRENT = 'SET_CURRENT';
const REMOVE_CURRENT = 'SET_CURRENT';

const UPDATE_COUNTER = 'UPDATE_COUNTER';
const INCREASE_DROPPEDELEMENT = 'INCREASE_DROPPEDELEMENT';
const CHANGE_POSITION='CHANGE_POSITION';

const SET_IFMOBILE = 'SET_IFMOBILE';

const DELETE_ITEM = 'DELETE_ITEM';
const SET_DROPDIRECTION= 'SET_DROPDIRECTION';

const SET_DRAGGEDCONSTRUCTOR= 'SET_DRAGGEDCONSTRUCTOR';

const SET_TOTALSUM = 'SET_TOTALSUM';

const REPLACE_BUN = 'REPLACE_BUN';



const SET_ALLINGREDIENTS_REQUEST = 'SET_ALLINGREDIENTS_REQUEST';
const SET_ALLINGREDIENTS_SUCCESS = 'SET_ALLINGREDIENTS_SUCCESS';
const SET_ALLINGREDIENTS_FAILURE = 'SET_ALLINGREDIENTS_FAILURE';

const GET_ORDERDATA_REQUEST='GET_ORDERDATA_REQUEST';
const GET_ORDERDATA_SUCCESS='GET_ORDERDATA_SUCCESS';
const GET_ORDERDATA_FAILURE='GET_ORDERDATA_FAILURE';
const NULL_ORDERDATA='NULL_ORDERDATA';

const SET_IFMOBILEORDERED='SET_IFMOBILEORDERED';
const SET_MODALINGREDIENTS= 'SET_MODALINGREDIENTS';
const REMOVE_MODALINGREDIENTS = 'REMOVE_MODALINGREDIENTS';
const SET_WINDOWDATA = 'SET_WINDOWDATA';

const OPEN_MOBILEMENU = 'OPEN_MOBILEMENU';

const CLOSE_MOBILEMENU='CLOSE_MOBILEMENU';

const UNFOLD_SUBMOBILEMENU='UNFOLD_SUBMOBILEMENU';

const FOLD_SUBMOBILEMENU= 'FOLD_SUBMOBILEMENU';
const SET_TOUCHEDITEM = 'SET_TOUCHEDITEM';
const CLEAR_TOUCHEDITEM = 'CLEAR_TOUCHEDITEM';

const GOUP_POSITION= 'GOUP_POSITION';

const GODOWN_POSITION='GODOWN_POSITION';
export {
  SET_INGREDIENTSBYCAT,
  
  SET_ORDERDATA,
  SET_CURRENT,
  REMOVE_CURRENT,
  SET_IFMOBILE,
  UPDATE_COUNTER,
  INCREASE_DROPPEDELEMENT,
  CHANGE_POSITION,
  DELETE_ITEM,
  SET_DROPDIRECTION,
  SET_DRAGGEDCONSTRUCTOR,
  SET_TOTALSUM,
REPLACE_BUN,


SET_ALLINGREDIENTS_REQUEST,
    SET_ALLINGREDIENTS_SUCCESS,
    SET_ALLINGREDIENTS_FAILURE,

    GET_ORDERDATA_REQUEST,
    GET_ORDERDATA_SUCCESS,
    GET_ORDERDATA_FAILURE,
    NULL_ORDERDATA,

    SET_IFMOBILEORDERED,
    SET_MODALINGREDIENTS,
    REMOVE_MODALINGREDIENTS,
    SET_WINDOWDATA,
    OPEN_MOBILEMENU,
    CLOSE_MOBILEMENU,
    UNFOLD_SUBMOBILEMENU,
    FOLD_SUBMOBILEMENU,
    SET_TOUCHEDITEM,
    CLEAR_TOUCHEDITEM,
    GOUP_POSITION,
    GODOWN_POSITION
};
